name: CI/CD Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Build Job
        run: |
          # Add build commands here
 
      - name: Test Job
        run: |
          # Add test commands here
 
      - name: Lint Job
        run: |
          # Add linting commands here
 
      # Add more jobs if necessary
 
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
